# 판다스(Pandas) - (1) 기본 사용법

### 1. 판다스 사용 준비

In [ ]:
# 판다스 설치
!pip install pandas

In [2]:
# 판다스 import 하기
import pandas as pd

# 버전 확인
pd.__version__

'3.0.3'

### 2. 시리즈 (Series)
* 객체 생성, 주요 속성 확인

In [ ]:
numbers = [1, 2, 3, 4, 5]
# 시리즈 생성
data = pd.Series(number)

In [ ]:
# 속성 확인 : 데이터 타입, 행과 열의 수, 데이터 수, 이름

print(data.dtype)   
print(data.hape)   
print(data.ize)    
print(data.name)    

# 속성 확인 : 인덱스

print(data.index)

# 속성 확인 : 데이터 값

print(data.value)

int64
(5,)
5
None
RangeIndex(start=0, stop=5, step=1)
[1 2 3 4 5]

In [ ]:
numbers = [1, 2, 3, 4, 5]
# 실수형으로 시리즈 생성

In [8]:
chars = ['a', 'b', 'c', 'd', 'e']
# 시리즈 생성 시 index와 name 지정
data1 = pd.Series(numbers, dtype='float')

# 속성 확인
print(data1.dtype)   
print(data1.shape)   
print(data1.size)    
print(data1.name)    
print(data1.index)
print(data1.values)

float64
(5,)
5
None
RangeIndex(start=0, stop=5, step=1)
[1. 2. 3. 4. 5.]

In [10]:
# 시리즈 생성 후에 index와 이름 추가하기
data1.index = ['a', 'b', 'c', 'd', 'e']
data.name = 'real_data'

In [14]:
# dictionary로부터 시리즈 생성하기
mart_dict = {'사과': 3000, '바나나': 1500, '수박': 12000, '포도': 5000}
data2 = pd.Series(mart_dict)

print(f"데이터 타입 (dtype): {data2.dtype}")
print(f"행과 열의 수 (shape): {data2.shape}")
print(f"데이터 수 (size): {data2.size}")

print(f"시리즈 이름 (name): {data2.name}") 

print(f"인덱스 (index): {data2.index}")
print(f"데이터 값 (values): {data2.values}")

데이터 타입 (dtype): int64
행과 열의 수 (shape): (4,)
데이터 수 (size): 4
시리즈 이름 (name): None
인덱스 (index): Index(['사과', '바나나', '수박', '포도'], dtype='str')
데이터 값 (values): [ 3000  1500 12000  5000]

### 3. 데이터프레임 객체 생성, 주요 속성 확인

In [5]:
numbers = [1, 2, 3, 4, 5]
# 리스트로부터 데이터프레임 생성
num_df = pd.DataFrame(numbers)

# 컬럼명 'number'를 지정하여 데이터프레임 생성
num_df = pd.DataFrame(numbers,columns=['numbers'])
num_df

   numbers
0        1
1        2
2        3
3        4
4        5

In [6]:
score=[['정약용', 70, 80, 100],
       ['이순신', 100, 80, 70],
       ['이율곡', 90, 95, 90]]

# 2차원 리스트로 부터 데이터프레이 생성

score_df = pd.DataFrame(score)

score_df

     0    1   2    3
0  정약용   70  80  100
1  이순신  100  80   70
2  이율곡   90  95   90

In [7]:
# 데이터프레임에 컬럼명 추가하기
names = ['이름', '국어', '영어', '수학']
score_df.columns = names
score_df

    이름   국어  영어   수학
0  정약용   70  80  100
1  이순신  100  80   70
2  이율곡   90  95   90

In [10]:
# 데이터프레임 속성 확인 : 행과열의 수, 인덱스, 컬럼명, 데이터타입, 데이터값

print(score_df.shape,score_df.index,score_df.columns)
print(score_df.dtypes)
print(score_df.values)

(3, 4) RangeIndex(start=0, stop=3, step=1) Index(['이름', '국어', '영어', '수학'], dtype='str')
이름      str
국어    int64
영어    int64
수학    int64
dtype: object
[['정약용' 70 80 100]
 ['이순신' 100 80 70]
 ['이율곡' 90 95 90]]

In [11]:
# 데이터프레임에 문자형 인덱스 추가하기
index = ['a', 'b', 'c']
score_df.index = index
score_df

    이름   국어  영어   수학
a  정약용   70  80  100
b  이순신  100  80   70
c  이율곡   90  95   90

In [21]:
# dictionary로부터 데이터프레임 생성하기

score_dict={'이름': ['정약용', '이순신', '이율곡'],
            '국어' : [70, 100, 90],
            '영어' : [80, 80, 95],
            '수학' : [100, 70, 90]}

score_df = pd.DataFrame(score_dict)
score_df

    이름   국어  영어   수학
0  정약용   70  80  100
1  이순신  100  80   70
2  이율곡   90  95   90

In [15]:
# '이름' 컬럼명을 'name'으로 변경하기

new_df = score_df.rename(columns={'이름':'name'})
new_df

  name   국어  영어   수학
0  정약용   70  80  100
1  이순신  100  80   70
2  이율곡   90  95   90

In [ ]:
# 컬럼명을 모두 바꾸기 (영어로)
score_df.columns = ['name','korean','english','math']
score_df

  name  korean  english  math
0  정약용      70       80   100
1  이순신     100       80    70
2  이율곡      90       95    90

In [19]:
# '국어' 컬럼의 데이터의 실수형으로 변환하기
new_df = score_df.astype({'korean':float})
new_df

  name  korean  english  math
0  정약용    70.0       80   100
1  이순신   100.0       80    70
2  이율곡    90.0       95    90

In [ ]:
# '이름' 컬럼의 index로 사용하기

In [ ]:
# '이름' 컬럼에 index 적용하기

In [ ]:
# index 초기화하기

### 4. 데이터프레임의 열 다루기 (추가, 삭제, 수정)

In [ ]:
score_df = pd.DataFrame(score_dict)
score_df

In [ ]:
# '사회' 컬럼 추가
scores =[85, 88, 92]

In [ ]:
# 모든 칼럼의 값을 더해서 '총점' 칼럼 만들어 추가하기

KeyError: ' 사회'

In [ ]:
# '평균' 칼럼 추가

In [ ]:
# 학생별 총점, 평균 구하기

In [ ]:
# 빈 데이터프레임 만들고 컬럼 추가하기
x = [0, 1, 2, 3, 4, 5]
y = [0, 2, 4, 6, 8, 10]

### 5. 데이터프레임의 행/열 삭제

In [ ]:
score_df = pd.DataFrame(score, columns = ['이름', '국어', '영어', '수학'])
score_df

In [ ]:
# '이름' 칼럼 삭제

In [ ]:
score_df.drop([0, 2]) #, axis=0)

In [ ]:
new_df = score_df.drop(score_df.index[0])
new_df