## 1. 파이썬 파일 처리

In [11]:
sample_file = 'data/sample.txt'

In [12]:
# 파일을 open하여 전체 내용을 읽어서 출력
with open(sample_file,mode='rt') as f:
    contents = f.read()
    print(contents)
print("----- 끝 -----")

나의 속도로

조금 늦어도 괜찮다.
남들과 같은 길을 갈 필요도 없다.

오늘 배운 것 하나,
오늘 해결한 문제 하나가
조금씩 나의 실력이 된다.

결과가 보이지 않는 날에도
나는 앞으로 가고 있다.

빠르게 가는 것보다
멈추지 않는 것이 중요하다.

오늘의 작은 한 걸음이
내일의 나를 만든다.

나는 늦은 것이 아니라
나의 속도로 가고 있다.

----- 끝 -----

In [13]:
# 파일을 open하고 한 줄씩 읽어서 출력하기
with open(sample_file,mode='r') as f:
    lines = f.readlines()
    for line in lines:
        print(line, end="")

print("----- 끝 -----")

나의 속도로

조금 늦어도 괜찮다.
남들과 같은 길을 갈 필요도 없다.

오늘 배운 것 하나,
오늘 해결한 문제 하나가
조금씩 나의 실력이 된다.

결과가 보이지 않는 날에도
나는 앞으로 가고 있다.

빠르게 가는 것보다
멈추지 않는 것이 중요하다.

오늘의 작은 한 걸음이
내일의 나를 만든다.

나는 늦은 것이 아니라
나의 속도로 가고 있다.
----- 끝 -----

In [14]:
# 파일객체에서 한 줄씩 읽어 오기
# 파일 객체 f를 반복문에서 사용하면 파일을 한 줄씩 읽으며,
# 각 줄 끝의 \n도 포함해서 가져옵
with open(sample_file, mode="r") as f:
    for line in f:
        print(line, end="")

print("----- 끝 -----")

나의 속도로

조금 늦어도 괜찮다.
남들과 같은 길을 갈 필요도 없다.

오늘 배운 것 하나,
오늘 해결한 문제 하나가
조금씩 나의 실력이 된다.

결과가 보이지 않는 날에도
나는 앞으로 가고 있다.

빠르게 가는 것보다
멈추지 않는 것이 중요하다.

오늘의 작은 한 걸음이
내일의 나를 만든다.

나는 늦은 것이 아니라
나의 속도로 가고 있다.
----- 끝 -----

In [15]:
# 여러 개의 파일 읽기 (모든 txt 파일을 읽어서 출력하기)
import glob
files = glob.glob("data/*.txt")
print(files)

for file in files:
    with open(file,mode="r") as f:
        print(f.read())
    print("---- 끝 ----")
print("----- 끝 -----")

['data/score.txt', 'data/hello.txt', 'data/sample.txt']
90
100
85
95
---- 끝 ----
안녕하세요
hello
내용을 추가합니다.
저장하는 문서 이름,  'w' 대신 'a'를 사용합니다.

---- 끝 ----
나의 속도로

조금 늦어도 괜찮다.
남들과 같은 길을 갈 필요도 없다.

오늘 배운 것 하나,
오늘 해결한 문제 하나가
조금씩 나의 실력이 된다.

결과가 보이지 않는 날에도
나는 앞으로 가고 있다.

빠르게 가는 것보다
멈추지 않는 것이 중요하다.

오늘의 작은 한 걸음이
내일의 나를 만든다.

나는 늦은 것이 아니라
나의 속도로 가고 있다.

---- 끝 ----
----- 끝 -----

## 2. 파이썬 문자열 다루기

In [16]:
# 양쪽 공백 제거
b1=" 작은 일에 성실한 사람은      큰일에도 성실하고 "
print(b1.strip())

작은 일에 성실한 사람은      큰일에도 성실하고

In [17]:
# 왼쪽 문자, 오른쪽 문자, 양쪽 문자 제거
text="....작은 일에 성실한 사람은, 큰일에도 성실하고...."
print(text.lstrip("."))
print(text.rstrip("."))
print(text.strip("."))

작은 일에 성실한 사람은, 큰일에도 성실하고....
....작은 일에 성실한 사람은, 큰일에도 성실하고
작은 일에 성실한 사람은, 큰일에도 성실하고

In [18]:
# ,로 문자열 분리
text="....작은 일에 성실한 사람은, 큰일에도 성실하고...."
print(text.split(","))

['....작은 일에 성실한 사람은', ' 큰일에도 성실하고....']

In [19]:
# .으로 문자열 분리
numbers="1. 2. 3. 4. 5. 6"
print(numbers.split("."))
num_list = map(int,numbers.split("."))

['1', ' 2', ' 3', ' 4', ' 5', ' 6']

## 3. 판다스로 데이터 가져오기

In [20]:
# 판다스 설치
!pip install pandas

Requirement already satisfied: pandas in /home/user/anaconda3/lib/python3.14/site-packages (3.0.3)
Requirement already satisfied: numpy>=2.3.3 in /home/user/anaconda3/lib/python3.14/site-packages (from pandas) (2.4.6)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/user/anaconda3/lib/python3.14/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /home/user/anaconda3/lib/python3.14/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [21]:
# 타이타닉 데이터 가져오기
titanic_data = 'https://raw.githubusercontent.com/sehakflower/data/main/titanic.csv'

In [22]:
# 데이터를 읽으면서 탭을 기준으로 분리하여 데이터 프레임으로 만들기
import pandas as pd
t_df = pd.read_csv(titanic_data, sep="\t")
t_df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
151,152,1,1,"Pears, Mrs. Thomas (Edith Wearne)",female,22.0,1,0,113776,66.6000,C2,S
152,153,0,3,"Meo, Mr. Alfonzo",male,55.5,0,0,A.5. 11206,8.0500,NaN,S
153,154,0,3,"van Billiard, Mr. Austin Blyler",male,40.5,0,2,A/5. 851,14.5000,NaN,S
154,155,0,3,"Olsen, Mr. Ole Martin",male,NaN,0,0,Fa 265302,7.3125,NaN,S
155,156,0,1,"Williams, Mr. Charles Duane",male,51.0,0,1,PC 17597,61.3792,NaN,C

In [23]:
# 연습용 sample_data.csv 로딩하기
sample_file = 'data/sample_data.csv'
import pandas as pd
sample_df = pd.read_csv(sample_file)
sample_df

      Name   Age Gender         City
0    Alice  24.0      F     New York
1      Bob   NaN      M  Los Angeles
2  Charlie  22.0      M          NaN
3    David  29.0      M      Chicago
4   Edward   NaN      M      Houston
5    Alice  24.0      F     New York
6    Susan  32.0      F      Houston

# 4. 판다스 데이터 처리

### 4-1. 데이터 구조 및 구성 확인

In [24]:
# 앞부분 확인
t_df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [25]:
# 뒷부분 확인
t_df.tail()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
151,152,1,1,"Pears, Mrs. Thomas (Edith Wearne)",female,22.0,1,0,113776,66.6000,C2,S
152,153,0,3,"Meo, Mr. Alfonzo",male,55.5,0,0,A.5. 11206,8.0500,NaN,S
153,154,0,3,"van Billiard, Mr. Austin Blyler",male,40.5,0,2,A/5. 851,14.5000,NaN,S
154,155,0,3,"Olsen, Mr. Ole Martin",male,NaN,0,0,Fa 265302,7.3125,NaN,S
155,156,0,1,"Williams, Mr. Charles Duane",male,51.0,0,1,PC 17597,61.3792,NaN,C

In [26]:
# 데이터 개수/형태 확인
t_df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
151,152,1,1,"Pears, Mrs. Thomas (Edith Wearne)",female,22.0,1,0,113776,66.6000,C2,S
152,153,0,3,"Meo, Mr. Alfonzo",male,55.5,0,0,A.5. 11206,8.0500,NaN,S
153,154,0,3,"van Billiard, Mr. Austin Blyler",male,40.5,0,2,A/5. 851,14.5000,NaN,S
154,155,0,3,"Olsen, Mr. Ole Martin",male,NaN,0,0,Fa 265302,7.3125,NaN,S
155,156,0,1,"Williams, Mr. Charles Duane",male,51.0,0,1,PC 17597,61.3792,NaN,C

In [27]:
#데이터의 기본 통계치 보기
t_df.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,156.000000,156.000000,156.000000,126.000000,156.000000,156.000000,156.000000
mean,78.500000,0.346154,2.423077,28.141508,0.615385,0.397436,28.109587
std,45.177428,0.477275,0.795459,14.613880,1.056235,0.870146,39.401047
min,1.000000,0.000000,1.000000,0.830000,0.000000,0.000000,6.750000
25%,39.750000,0.000000,2.000000,19.000000,0.000000,0.000000,8.003150
50%,78.500000,0.000000,3.000000,26.000000,0.000000,0.000000,14.454200
75%,117.250000,1.000000,3.000000,35.000000,1.000000,0.000000,30.371850
max,156.000000,1.000000,3.000000,71.000000,5.000000,5.000000,263.000000

In [28]:
# 데이터 구성 정보 확인하기
t_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 156 entries, 0 to 155
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  156 non-null    int64
 1   Survived     156 non-null    int64
 2   Pclass       156 non-null    int64
 3   Name         156 non-null    str
 4   Sex          156 non-null    str
 5   Age          126 non-null    float64
 6   SibSp        156 non-null    int64
 7   Parch        156 non-null    int64
 8   Ticket       156 non-null    str
 9   Fare         156 non-null    float64
 10  Cabin        31 non-null     str
 11  Embarked     155 non-null    str
dtypes: float64(2), int64(5), str(5)
memory usage: 21.0 KB

In [29]:
# 타이타닉 데이터 구조 및 구성 확인하기 
sample_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    7 non-null      str
 1   Age     5 non-null      float64
 2   Gender  7 non-null      str
 3   City    6 non-null      str
dtypes: float64(1), str(3)
memory usage: 448.0 bytes

### 4-2. 컬럼명과 인덱스 정리

In [101]:
# 컬럼명의 첫글자는 소문자로, 나머지는 대문자로 수정 : lambda 함수사용
t_df.rename(
    columns=lambda x: x[0].lower() + x[1:].upper(),
    inplace=True
)

In [65]:
# 데이터프레임 복사하기
sample_backup_df = sample_df.copy()
sample_backup_df

      Name   Age Gender         City
0    Alice  24.0      F     New York
1      Bob   NaN      M  Los Angeles
2  Charlie  22.0      M          NaN
3    David  29.0      M      Chicago
4   Edward   NaN      M      Houston
5    Alice  24.0      F     New York
6    Susan  32.0      F      Houston

In [66]:
# 열 이름 변경하기 : 모두 소문자로 변경
new_cols = []
for col in sample_df.columns:
    new_cols.append(col.lower())
sample_df.columns = new_cols
sample_df

      name   age gender         city
0    Alice  24.0      F     New York
1      Bob   NaN      M  Los Angeles
2  Charlie  22.0      M          NaN
3    David  29.0      M      Chicago
4   Edward   NaN      M      Houston
5    Alice  24.0      F     New York
6    Susan  32.0      F      Houston

In [32]:
# index 확인

In [33]:
# 행 데이터 삭제하기
drop_index = [2, 4, 152, 154]

In [34]:
# index를 0부터 순서대로 assign 되도록 reset하기

In [ ]:
# 컬럼 PassengeId를 index로 설정하기
t_df.set_index(PassengerId)

In [100]:
# 현재 index (passengerid) 를 컬럼으로 만들고, index를 RangeIndex로 reset하기
t_df = t_df.reset_index()

### 4-3. 데이터 정렬

In [97]:
# 'age' 기준으로 정렬
t_df.sort_values(by='Age',ascending=False)
t_df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
151,152,1,1,"Pears, Mrs. Thomas (Edith Wearne)",female,22.0,1,0,113776,66.6000,C2,S
152,153,0,3,"Meo, Mr. Alfonzo",male,55.5,0,0,A.5. 11206,8.0500,NaN,S
153,154,0,3,"van Billiard, Mr. Austin Blyler",male,40.5,0,2,A/5. 851,14.5000,NaN,S
154,155,0,3,"Olsen, Mr. Ole Martin",male,NaN,0,0,Fa 265302,7.3125,NaN,S
155,156,0,1,"Williams, Mr. Charles Duane",male,51.0,0,1,PC 17597,61.3792,NaN,C

In [38]:
# 'age' 기준으로 내림차순으로 정렬

In [98]:
# 'age', 'pclass'를 기준으로 정렬
t_df.sort_values(by=['Pclass','Age']) 

# pclass는 오름차순으로 정렬, age는 내림차순으로 
t_df.sort_values(
    by=['Pclass', 'Age'],
    ascending=[True, False]
)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
96,97,0,1,"Goldschmidt, Mr. George B",male,71.0,0,0,PC 17754,34.6542,A5,C
54,55,0,1,"Ostby, Mr. Engelhart Cornelius",male,65.0,0,1,113509,61.9792,B30,C
11,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,C103,S
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
124,125,0,1,"White, Mr. Percival Wayland",male,54.0,0,1,35281,77.2875,D26,S
...,...,...,...,...,...,...,...,...,...,...,...,...
121,122,0,3,"Moore, Mr. Leonard Charles",male,NaN,0,0,A4. 54510,8.0500,NaN,S
126,127,0,3,"McMahon, Mr. Martin",male,NaN,0,0,370372,7.7500,NaN,Q
128,129,1,3,"Peter, Miss. Anna",female,NaN,1,1,2668,22.3583,F E69,C
140,141,0,3,"Boulos, Mrs. Joseph (Sultana)",female,NaN,0,2,2678,15.2458,NaN,C
154,155,0,3,"Olsen, Mr. Ole Martin",male,NaN,0,0,Fa 265302,7.3125,NaN,S

In [40]:
# index를 기준으로 정렬

### 4-4. 데이터 접근/추출
* 범위 지정 : 직접 지정, 인덱서 이용
* 조건 지정

In [70]:
score_dict={'이름': ['정약용', '이순신', '이율곡', '홍길동'],
            '국어' : [70, 100, 90, 85],
            '영어' : [80, 80, 95, 100],
            '수학' : [100, 70, 90, 90]}
score_df = pd.DataFrame(score_dict)
score_df

    이름   국어   영어   수학
0  정약용   70   80  100
1  이순신  100   80   70
2  이율곡   90   95   90
3  홍길동   85  100   90

In [ ]:
# 행 지정 -> 슬라이싱
score_df[2:3]

In [ ]:
# 열 접근
score_df['이름']

In [71]:
# 특정 (행,열)의 데이터 접근
score_df[1:2][['이름','국어']]

    이름   국어
1  이순신  100

In [72]:
# 인덱서 이용 : 레이블(이름) 인덱서
# 행 접근
score_df.loc[1]

이름    이순신
국어    100
영어     80
수학     70
Name: 1, dtype: object

In [ ]:
# 열 접근
score_df.loc[:,['이름','국어']]

In [47]:
# (행,열) 접근

In [ ]:
# 인덱서 이용 : 위치(숫자) 인덱서
# 행 접근
score_df.iloc[:1]

In [ ]:
# 열 접근
score_df.iloc[:,1:3]

In [ ]:
# (행,열) 접근
score_df.iloc[:2,1:3]

In [73]:
# 조건 지정 추출 : Boolean Indexing
# 직접 지정 방식으로 행 추출
score_df[score_df.수학 >= 90 ]

    이름  국어   영어   수학
0  정약용  70   80  100
2  이율곡  90   95   90
3  홍길동  85  100   90

In [74]:
score_df[(score_df.국어 >= 90) & (score_df.수학 >= 90)]

    이름  국어  영어  수학
2  이율곡  90  95  90

In [93]:
score_df[score_df.이름.isin(['정약용','이순신'])]

    이름   국어  영어   수학
0  정약용   70  80  100
1  이순신  100  80   70

In [52]:
# 인덱서 방식으로 행 추출

In [53]:
# (행,열) 데이터 추출

In [54]:
# 열 데이터에 조건 지정

## 4-5. 그룹별로 요약하여 데이터 확인
* value_counts()
* groupby()
* pivot_table()

In [1]:
sample_file = 'data/sales_sample.csv'

In [2]:
# 샘플 파일 로딩
import pandas as pd
sales_df = pd.read_csv(sample_file)
sales_df

    지역   상품  판매수량   매출
0   서울  노트북     2  120
1   서울  태블릿     1   80
2   부산  노트북     2  100
3   부산  태블릿     1   70
4   서울  노트북     3  150
5   부산  노트북     1  110
6   대전  노트북     2  130
7   대전  태블릿     2   90
8   서울  태블릿     2  160
9   부산  태블릿     3  210
10  대전  노트북     1   65
11  대전  태블릿     1   45
12  서울  노트북     1   60
13  부산  노트북     3  150
14  대전  노트북     2  120
15  서울  태블릿     2  160
16  부산  태블릿     1   70
17  대전  태블릿     3  135
18  서울  노트북     2  120
19  부산  태블릿     2  140

In [ ]:
# 지역별 판매 기록의 개수
sales_df['지역'].value_counts()

In [3]:
# 상품별 판매 기록의 개수와 비율
sales_df['상품'].value_counts()

상품
노트북    10
태블릿    10
Name: count, dtype: int64

In [4]:
sales_df['상품'].value_counts(normalize=True)

상품
노트북    0.5
태블릿    0.5
Name: proportion, dtype: float64

In [6]:
# 지역과 상품의 조합별 판매 기록 개수
sales_df.value_counts(['지역','상품'])

지역  상품
서울  노트북    4
부산  태블릿    4
서울  태블릿    3
부산  노트북    3
대전  노트북    3
    태블릿    3
Name: count, dtype: int64

In [7]:
sample_df = pd.read_csv('data/sample_data.csv')
sample_df

      Name   Age Gender         City
0    Alice  24.0      F     New York
1      Bob   NaN      M  Los Angeles
2  Charlie  22.0      M          NaN
3    David  29.0      M      Chicago
4   Edward   NaN      M      Houston
5    Alice  24.0      F     New York
6    Susan  32.0      F      Houston

In [ ]:
sample_df['City'].value_counts(dropna=False, ascending=True)

City
New York       2
Houston        2
Los Angeles    1
NaN            1
Chicago        1
Name: count, dtype: int64

In [15]:
# 지역별 총매출
sales_df.groupby(by='지역').sum()

                       상품  판매수량   매출
지역
대전     노트북태블릿노트북태블릿노트북태블릿    11  585
부산  노트북태블릿노트북태블릿노트북태블릿태블릿    13  850
서울  노트북태블릿노트북태블릿노트북태블릿노트북    13  850

In [16]:
# 상품별 평균 매출
sales_df.groupby(by='상품')['매출'].mean()

상품
노트북    112.5
태블릿    116.0
Name: 매출, dtype: float64

In [18]:
# 지역별 판매수량의 합계와 매출의 합계
sales_df.groupby(by='지역')[['판매수량','매출']].sum()

    판매수량   매출
지역
대전    11  585
부산    13  850
서울    13  850

In [19]:
# 지역과 상품별 평균 매출
sales_df.groupby(by=['지역','상품'])['매출'].mean()

지역  상품
대전  노트북    105.000000
    태블릿     90.000000
부산  노트북    120.000000
    태블릿    122.500000
서울  노트북    112.500000
    태블릿    133.333333
Name: 매출, dtype: float64

In [20]:
sales_df.pivot_table(
    values='매출',
    aggfunc='sum',
    index='지역',
    columns='상품'
)

상품  노트북  태블릿
지역
대전  315  270
부산  360  490
서울  450  400

In [21]:
# 지역별·상품별 총매출을 구하고 행과 열의 합계 표시
sales_df.pivot_table(
    index='상품',
    columns='지역',
    values='매출',
    aggfunc='sum'
)

지역    대전   부산   서울
상품
노트북  315  360  450
태블릿  270  490  400

In [22]:
# 지역별 매출 : 건수, 합계, 평균, 최대값
sales_df.groupby(by='지역')['매출'].agg(['count','sum','mean','max'])

    count  sum        mean  max
지역
대전      6  585   97.500000  135
부산      7  850  121.428571  210
서울      7  850  121.428571  160

## 5-1. 결측치 처리

In [2]:
import pandas as pd
sample_df = pd.read_csv('data/sample_data.csv')
sample_df

      Name   Age Gender         City
0    Alice  24.0      F     New York
1      Bob   NaN      M  Los Angeles
2  Charlie  22.0      M          NaN
3    David  29.0      M      Chicago
4   Edward   NaN      M      Houston
5    Alice  24.0      F     New York
6    Susan  32.0      F      Houston

In [3]:
sample_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    7 non-null      str
 1   Age     5 non-null      float64
 2   Gender  7 non-null      str
 3   City    6 non-null      str
dtypes: float64(1), str(3)
memory usage: 448.0 bytes

In [8]:
# isna
sample_df.isna().sum()

Name      0
Age       2
Gender    0
City      1
dtype: int64

In [10]:
# isnull
sample_df.isnull().sum()

Name      0
Age       2
Gender    0
City      1
dtype: int64

In [12]:
#결측치가 있는 데이터 확인
# 'Age' 컬럼에 결측치가 있는지와 결측치 데이터확인
print(sample_df['Age'].isna().sum())
sample_df[sample_df['Age'].isna()]

2

     Name  Age Gender         City
1     Bob  NaN      M  Los Angeles
4  Edward  NaN      M      Houston

In [15]:
# 어떤 컬럼에든 결측치가 있는 데이터의 갯수, 데이터 확인
na_df = sample_df[sample_df.isna().any(axis=1)]
print(len(na_df))
na_df

3

      Name   Age Gender         City
1      Bob   NaN      M  Los Angeles
2  Charlie  22.0      M          NaN
4   Edward   NaN      M      Houston

In [17]:
sample_df.dropna(subset=['City'])

     Name   Age Gender         City
0   Alice  24.0      F     New York
1     Bob   NaN      M  Los Angeles
3   David  29.0      M      Chicago
4  Edward   NaN      M      Houston
5   Alice  24.0      F     New York
6   Susan  32.0      F      Houston

In [51]:
# Age 결측치는 Age의 평균값으로 채우기
age_avg = sample_df['Age'].mean()
sample_df['Age'].fillna(sample_df['Age'].mean())

0    24.0
1    26.2
2    22.0
3    29.0
4    26.2
5    24.0
6    32.0
Name: Age, dtype: float64